export const dynamic='force-dynamic';
import {requireUser} from '@/lib/auth';
import db from '@/lib/db';
import VisualBaselineControls from '@/components/VisualBaselineControls';
function parse(v:string){try{return JSON.parse(v||'{}')}catch{return {}}}
export default async function Page(){await requireUser();
 const rows:any[]=db.prepare(`SELECT c.*,r.started_at FROM check_results c JOIN runs r ON r.id=c.run_id WHERE c.visual_json IS NOT NULL AND c.visual_json!='{}' ORDER BY c.id DESC LIMIT 60`).all() as any[];
 const latest=new Map<string,any>(); for(const r of rows){const k=`${r.monitor}|${r.device}`;if(!latest.has(k))latest.set(k,r)}
 return <><div className="eyebrow">Visual regression</div><h1 className="title">Visual Monitoring</h1><p className="muted pageintro">Pixel-level comparison against the stored baseline for each customer journey and device. The first successful capture creates the baseline automatically.</p><div className="monitorgrid">{[...latest.values()].map((r:any)=>{const v=parse(r.visual_json);const bad=v.status==='changed';return <div className="card monitor" key={r.id}><div className="split"><div><h2>{r.monitor}</h2><p className="muted">{r.device}</p></div><span className={`status ${bad?'badbg':''}`}>{v.baseline_created?'BASELINE':bad?'CHANGED':'MATCH'}</span></div><div className="metric">{typeof v.diff_percent==='number'?`${v.diff_percent.toFixed(2)}%`:'—'}</div><p className="muted">visual difference · threshold {v.threshold_percent ?? '—'}%</p>{v.current_path&&<div className="visualcompare"><figure><figcaption>Baseline</figcaption><img src={`/api/visual-image?kind=baseline&key=${String(v.baseline_path||'').split('/').pop()?.replace('.png','')}`}/></figure><figure><figcaption>Current</figcaption><img src={`/api/visual-image?kind=current&key=${String(v.current_path||'').split('/').pop()?.replace('.png','')}`}/></figure></div>}<div className="monitorfoot"><span>{new Date(r.started_at).toLocaleString('en-GB')}</span><span>{v.width||'—'}×{v.height||'—'}</span></div></div>})}{!latest.size&&<div className="card full empty"><b>No visual baselines yet</b><span>Run the synthetic monitors once to create them.</span></div>}</div><div className="card" style={{marginTop:16}}><h2>How it works</h2><p className="muted">A baseline is stored in the persistent JTS Monitor data volume for each monitor/device combination. Later runs compare the rendered page with that baseline and record the percentage of changed pixels. Baselines survive container replacement.</p><p className="notice">Dynamic content can legitimately change pixels. Use the Visual threshold in Settings to tune sensitivity.</p><VisualBaselineControls/></div></>
}
