import {spawn} from 'child_process';
import Database from 'better-sqlite3';
import fs from 'fs'; import path from 'path';
const dir=process.env.DATA_DIR||'/data'; fs.mkdirSync(dir,{recursive:true});
const db=new Database(path.join(dir,'jts-monitor.db')); db.pragma('journal_mode = WAL'); db.pragma('busy_timeout = 5000');
db.exec(`CREATE TABLE IF NOT EXISTS runs(id INTEGER PRIMARY KEY AUTOINCREMENT,started_at TEXT NOT NULL,finished_at TEXT,status TEXT NOT NULL,duration_ms INTEGER DEFAULT 0,passed INTEGER DEFAULT 0,failed INTEGER DEFAULT 0,output TEXT DEFAULT '');CREATE TABLE IF NOT EXISTS incidents(id INTEGER PRIMARY KEY AUTOINCREMENT,opened_at TEXT NOT NULL,resolved_at TEXT,status TEXT NOT NULL,summary TEXT NOT NULL);CREATE TABLE IF NOT EXISTS run_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,requested_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending');CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);INSERT OR IGNORE INTO settings(key,value) VALUES('interval_minutes','5');INSERT OR IGNORE INTO settings(key,value) VALUES('failure_threshold','2');INSERT OR IGNORE INTO settings(key,value) VALUES('retention_days','30');`);
let busy=false;
function setting(key:string,fallback:number){const row=db.prepare('SELECT value FROM settings WHERE key=?').get(key) as any;return Number(row?.value||fallback)}
function parseCounts(out:string,code:number){const m=out.match(/(\d+) passed/); const f=out.match(/(\d+) failed/); return {passed:m?Number(m[1]):code===0?4:0,failed:f?Number(f[1]):code===0?0:1}}
async function run(requestId?:number){if(busy)return;busy=true;if(requestId)db.prepare("UPDATE run_requests SET status='running' WHERE id=?").run(requestId);const start=Date.now(),started=new Date().toISOString();let out='';const p=spawn('npx',['playwright','test','e2e/checkout.spec.ts','--reporter=line'],{env:{...process.env,PLAYWRIGHT_HTML_OPEN:'never'}});p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>out+=d);p.on('close',code=>{const duration=Date.now()-start;const c=parseCounts(out,code||0);db.prepare('INSERT INTO runs(started_at,finished_at,status,duration_ms,passed,failed,output) VALUES(?,?,?,?,?,?,?)').run(started,new Date().toISOString(),code===0?'pass':'fail',duration,c.passed,c.failed,out.slice(-50000));if(requestId)db.prepare("UPDATE run_requests SET status='done' WHERE id=?").run(requestId);const threshold=Math.max(1,setting('failure_threshold',2));const recent=db.prepare('SELECT status FROM runs ORDER BY id DESC LIMIT ?').all(threshold) as any[];if(recent.length===threshold&&recent.every(r=>r.status==='fail')&&!db.prepare("SELECT id FROM incidents WHERE status='open' LIMIT 1").get())db.prepare("INSERT INTO incidents(opened_at,status,summary) VALUES(?,'open',?)").run(new Date().toISOString(),`Production checkout failed ${threshold} consecutive synthetic runs`);if(code===0)db.prepare("UPDATE incidents SET status='resolved',resolved_at=? WHERE status='open'").run(new Date().toISOString());const retention=Math.max(1,setting('retention_days',30));db.prepare("DELETE FROM runs WHERE datetime(started_at) < datetime('now', ?)").run(`-${retention} days`);busy=false;});}
let nextScheduled=0;
setInterval(()=>{const req=db.prepare("SELECT id FROM run_requests WHERE status='pending' ORDER BY id LIMIT 1").get() as any;if(req&&!busy){run(req.id);return;}const interval=Math.max(1,setting('interval_minutes',5))*60000;if(Date.now()>=nextScheduled&&!busy){nextScheduled=Date.now()+interval;run();}},1000);
